app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user/

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"