UserBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        country:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
