app_home_page:
    path:  /
    defaults: { _controller: 'AppBundle:Default:index' }
    options:
        expose: true

app_report_page:
    path: /report
    defaults: { _controller: 'AppBundle:Default:report' }
    options:
        expose: true

app_test_page:
    path: /test
    defaults: { _controller: 'AppBundle:Default:test' }
    options:
        expose: true
rest :
    type : rest
    resource : "@AppBundle/Resources/config/routing_rest.yml"
    prefix : /api
    options:
        expose: true