AppBundle\Entity\Client:
    type:  entity
    table: clients
    repositoryClass: AppBundle\Entity\ClientRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        country:
            type: string
            length: 2
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
    oneToOne:
        wallet:
            targetEntity: AppBundle\Entity\Wallet
            mappedBy: client
            fetch: EAGER