AppBundle\Entity\CurrencyRate:
    type:  entity
    table: currency_rate
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    uniqueConstraints:
        uniq_idx:
          columns: [ currency_id, createdAt, provider_name ]

    manyToOne:
        currency:
            targetEntity: AppBundle\Entity\Currency
            onDelete: CASCADE
            onUpdate: CASCADE