AppBundle\Entity\RateUsd:
    type: entity
    table: rate_usd
    repositoryClass: AppBundle\Entity\RateUsdRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        currency:
            type: string
            length: '3'
        rateValue:
            type: decimal
            precision: 8
            scale: 4
        rateDate:
            type: datetime
    lifecycleCallbacks: {  }
