<?php

namespace AppBundle\Entity;

/**
 * TransferHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
